parameters:
    sylius.order_fields:
        - "CheckoutCompletedAt"
        - "IsCheckoutCompleted"
        - "CheckoutState"
        - "Shipments"
        - "ShippingRequired"
        - "ShippingState"
        - "ShippingAddress"
        - "BillingAddress"
        - "Number"
        - "Notes"
        - "Items"
        - "ItemsTotal"
        - "Total"
        - "State"
        - "Adjustments"
        - "Customer"
        - "Payments"
        - "PaymentState"
        - "CurrencyCode"
        - "LocaleCode"
        - "Promotions"
        - "PromotionCoupon"
        - "TokenValue"
        - "CustomerIp"
        - "Channel"

services:
    sylius.exporter.orders.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\JsonResourceExporter
        arguments:
            - "@sylius.exporter.pluginpool.orders"
            - "%sylius.order_fields%"
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.order, format: json }

    sylius.exporter.pluginpool.orders:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\PluginPool
        arguments:
            - ["@sylius.exporter.plugin.resource.orders"]
            - "%sylius.order_fields%"

    sylius.exporter.plugin.resource.orders:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\OrderResourcePlugin
        arguments:
            - "@sylius.repository.order"
            - "@property_accessor"
            - "@doctrine.orm.entity_manager"
