parameters:
    sylius.product_association_types_fields: ["Code", "Translations"]

services:
    sylius.exporter.product_association_types.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\JsonResourceExporter
        arguments:
            - "@sylius.exporter.pluginpool.product_association_types"
            - "%sylius.product_association_types_fields%"
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.product_association_type, format: json }

    sylius.exporter.plugin.resource.product_association_types:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\ProductAssociationTypeResourcePlugin
        arguments:
            - "@sylius.repository.product_association_type"
            - "@property_accessor"
            - "@doctrine.orm.entity_manager"

    sylius.exporter.pluginpool.product_association_types:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\PluginPool
        arguments:
            - ["@sylius.exporter.plugin.resource.product_association_types"]
            - "%sylius.product_association_types_fields%"

    sylius.processor.product_association_types:
        class: FriendsOfSylius\SyliusImportExportPlugin\Processor\ProductAssociationTypeProcessor
        arguments:
            - "@sylius.factory.product_association_type"
            - "@sylius.repository.product_association_type"
            - "@sylius.manager.product_association_type"
            - "@sylius.importer.metadata_validator"
            - "%sylius.product_association_types_fields%"

    sylius.importer.product_association_types.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - "@sylius.manager.product_association_type"
            - "@sylius.processor.product_association_types"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: product_association_type, format: json }
