parameters:
    sylius.tax_categories_fields: ["Code", "Name", "Description"]

services:
    sylius.exporter.tax_categories.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\JsonResourceExporter
        arguments:
            - "@sylius.exporter.pluginpool.tax_categories"
            - "%sylius.tax_categories_fields%"
            - "@sylius.exporters_transformer_pool"
        tags:
            - { name: sylius.exporter, type: sylius.tax_category, format: json }


    sylius.exporter.pluginpool.tax_categories:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\PluginPool
        arguments:
            - ["@sylius.exporter.plugin.resource.tax_categories"]
            - "%sylius.tax_categories_fields%"

    sylius.processor.tax_categories:
        class: FriendsOfSylius\SyliusImportExportPlugin\Processor\ResourceProcessor
        arguments:
            - "@sylius.factory.tax_category"
            - "@sylius.repository.tax_category"
            - "@property_accessor"
            - "@sylius.importer.metadata_validator"
            - ["Code", "Name", "Description"]


    sylius.importer.tax_categories.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - "@sylius.manager.tax_category"
            - "@sylius.processor.tax_categories"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: tax_category, format: json }
