language: php

dist: trusty

sudo: false

cache:
    yarn: true
    directories:
        - ~/.composer/cache/files
        - $SYLIUS_CACHE_DIR

env:
    global:
        - SYLIUS_CACHE_DIR=$HOME/.sylius-cache
        - SYLIUS_BUILD_DIR=etc/build

matrix:
    include:
        # Sylius 1.3
        -
            php: 7.3
            env:
                - DEPENDENCY_VERSIONS="sylius/sylius:1.3.* symfony/symfony:4.2.*"
        -
            php: 7.2
            env:
                - DEPENDENCY_VERSIONS="sylius/sylius:1.3.* symfony/symfony:4.2.*"

before_install:
    - phpenv config-rm xdebug.ini
    - echo "memory_limit=4096M" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
    - mkdir -p "${SYLIUS_CACHE_DIR}"

install:
    - composer require ${DEPENDENCY_VERSIONS} --no-update
    - composer update --prefer-dist
    - (cd tests/Application && yarn install)

before_script:
    - (cd tests/Application && bin/console doctrine:database:create --env=test -vvv)
    - (cd tests/Application && bin/console doctrine:schema:create --env=test -vvv)
    - (cd tests/Application && bin/console cache:warmup --env=dev -vvv)

script:
    - composer validate --strict
    - composer analyse

    - bin/phpspec run
    - bin/phpunit
