## Export routes for specific settings
app_export_data_country:
    path: /export/sylius.country/{format}
    methods: [GET]
    defaults:
        resource: sylius.country
        _controller: sylius.controller.export_data:exportAction
        _sylius:
            filterable: true
            grid: sylius_admin_country

app_export_data_order:
    path: /export/sylius.order/{format}
    methods: [GET]
    defaults:
        resource: sylius.order
        _controller: sylius.controller.export_data:exportAction
        _sylius:
            filterable: true
            grid: sylius_admin_order

app_export_data_customer:
    path: /export/sylius.customer/{format}
    methods: [GET]
    defaults:
        resource: sylius.customer
        _controller: sylius.controller.export_data:exportAction
        _sylius:
            filterable: true
            grid: sylius_admin_customer

## Backup route
app_export_data:
    path: /export/{resource}/{format}
    methods: [GET]
    defaults:
        _controller: sylius.controller.export_data:exportAction
        _sylius:
            paginate: false
            filterable: false
