imports:
    - 'services/*.yml'

services:
    # Controllers for Admin-Integration
    sylius.controller.import_data:
        public: true
        class: FriendsOfSylius\SyliusImportExportPlugin\Controller\ImportDataController
        arguments:
            - "@sylius.importers_registry"
            - "@session"
            - "@form.factory"
            - "@twig"

    sylius.controller.export_data:
        public: true
        class: FriendsOfSylius\SyliusImportExportPlugin\Controller\ExportDataController
        arguments:
            - "@sylius.exporters_registry"
            - "@sylius.resource_controller.request_configuration_factory"
            - "@sylius.resource_controller.resources_collection_provider"

    # Form Type
    sylius.form.type.import:
        public: true
        class: FriendsOfSylius\SyliusImportExportPlugin\Form\ImportType
        arguments: ["@sylius.importers_registry"]
        tags: [form.type]

    # Registries for Importers / Exporters
    sylius.exporters_registry:
        public: true
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ExporterRegistry
        arguments:
            - FriendsOfSylius\SyliusImportExportPlugin\Exporter\ResourceExporterInterface
            - exporter

    sylius.importers_registry:
        public: true
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ImporterRegistry
        arguments:
            - FriendsOfSylius\SyliusImportExportPlugin\Importer\ImporterInterface
            - importer

    # Default export transformers and a default transformers pool
    sylius.exporters_transformer_pool:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Transformer\Pool
        arguments: [!tagged sylius.exporter_transformer]

    sylius.exporters_transformer_datetime:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Transformer\Handler\DateTimeToStringHandler
        tags:
            - { name: sylius.exporter_transformer }

    sylius.exporters_transformer_integer_money_format:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Transformer\Handler\IntegerToMoneyFormatHandler
        arguments:
            - ['Total']
        tags:
            - { name: sylius.exporter_transformer }

    # Commands
    sylius.command.import_data:
        class: FriendsOfSylius\SyliusImportExportPlugin\Command\ImportDataCommand
        arguments:
            - "@sylius.importers_registry"
        tags:
            - { name: 'console.command' }

    sylius.command.import_data_from_message_queue:
        class: FriendsOfSylius\SyliusImportExportPlugin\Command\ImportDataFromMessageQueueCommand
        arguments:
            - "@sylius.importers_registry"
        calls:
            - [ setContainer, ["@service_container"]]
        tags:
            - { name: 'console.command' }

    sylius.command.export_data:
        class: FriendsOfSylius\SyliusImportExportPlugin\Command\ExportDataCommand
        arguments:
            - "@sylius.exporters_registry"
        calls:
            - [ setContainer, ["@service_container"]]
        tags:
            - { name: 'console.command' }

    sylius.command.export_data_to_message_queue:
        class: FriendsOfSylius\SyliusImportExportPlugin\Command\ExportDataToMessageQueueCommand
        arguments:
            - "@sylius.exporters_registry"
        calls:
            - [ setContainer, ["@service_container"]]
        tags:
            - { name: 'console.command' }

    # Plugins for Exporters

    sylius.exporter.plugin.resource.tax_categories:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\ResourcePlugin
        arguments:
            - "@sylius.repository.tax_category"
            - "@property_accessor"
            - "@doctrine.orm.entity_manager"

    sylius.exporter.plugin.resource.customers:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\ResourcePlugin
        arguments:
            - "@sylius.repository.customer"
            - "@property_accessor"
            - "@doctrine.orm.entity_manager"

    # ORM hydrators to improve performance
    sylius.exporter.orm.hydrator.orders:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\ORM\Hydrator\OrderHydrator
        arguments:
            - "@sylius.repository.order"

    # PluginPools for Exporters. Can contain multiple Plugins
    sylius.exporter.pluginpool.customers:
        class: FriendsOfSylius\SyliusImportExportPlugin\Exporter\Plugin\PluginPool
        arguments:
            - ["@sylius.exporter.plugin.resource.customers"]
            - ["Email", "Email_canonical", "First_name" , "Last_name" ,  "Birthday", "Gender", "Phone_number", "Subscribed_to_newsletter"]

    # Service for gathering Information about Import
    sylius.importer.result:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\ImporterResult
        arguments:
            - "@debug.stopwatch"
    # Service for validating the header-information of input-files.
    sylius.importer.metadata_validator:
        class: FriendsOfSylius\SyliusImportExportPlugin\Processor\MetadataValidator

    # Service for concatenating the address.
    sylius.service.address_concatenation:
        class: FriendsOfSylius\SyliusImportExportPlugin\Service\DefaultAddressConcatenation

    # generic ResourceProcessors, which can work with just Property-Accessors
    sylius.processor.customer_groups:
        class: FriendsOfSylius\SyliusImportExportPlugin\Processor\ResourceProcessor
        arguments:
            - "@sylius.factory.customer_group"
            - "@sylius.repository.customer_group"
            - "@property_accessor"
            - "@sylius.importer.metadata_validator"
            - ["Code", "Name"]

    sylius.processor.customers:
        class: FriendsOfSylius\SyliusImportExportPlugin\Processor\ResourceProcessor
        arguments:
            - "@sylius.factory.customer"
            - "@sylius.repository.customer"
            - "@property_accessor"
            - "@sylius.importer.metadata_validator"
            - ["Email", "Email_canonical", "First_name" , "Last_name" ,  "Birthday", "Gender", "Phone_number", "Subscribed_to_newsletter"]

    FriendsOfSylius\SyliusImportExportPlugin\Synchronisation\Exporter:
        arguments:
            - "@service_container"
            - "@sylius.exporters_registry"

    FriendsOfSylius\SyliusImportExportPlugin\Synchronisation\Importer:
        arguments:
            - "@sylius.importers_registry"

    FriendsOfSylius\SyliusImportExportPlugin\Synchronisation\BackendSynchroniser:
        arguments:
            - "@gaufrette.friends_of_sylius_import_export_filesystem"
            - "@FriendsOfSylius\\SyliusImportExportPlugin\\Synchronisation\\Exporter"
            - "@FriendsOfSylius\\SyliusImportExportPlugin\\Synchronisation\\Importer"
            - "@doctrine.orm.default_entity_manager"
            - "@gaufrette.sylius_image_filesystem"
            - "@sylius.repository.product_image"
            - "@sylius.repository.taxon_image"

    FriendsOfSylius\SyliusImportExportPlugin\Formatter\DateTimeFormatter:
        public: true
