services:
    # JSON-Importers
    sylius.importer.customer_group.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - "@sylius.manager.customer_group"
            - "@sylius.processor.customer_groups"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: customer_group, format: json }

    sylius.importer.customers.json:
        class: FriendsOfSylius\SyliusImportExportPlugin\Importer\JsonResourceImporter
        arguments:
            - "@sylius.manager.customer"
            - "@sylius.processor.customers"
            - "@sylius.importer.result"
            - "%sylius.importer.batch_size%"
            - "%sylius.importer.fail_on_incomplete%"
            - "%sylius.importer.stop_on_failure%"
        tags:
            - { name: sylius.importer, type: customer, format: json }
